// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3WthCdwEM9JILp_2fBJSKX5HTpuZxpk',
    appId: '1:329358166515:web:63495267ee522c442c2a86',
    messagingSenderId: '329358166515',
    projectId: 'teamtracking-96377',
    authDomain: 'teamtracking-96377.firebaseapp.com',
    storageBucket: 'teamtracking-96377.appspot.com',
    measurementId: 'G-FK3JHVGL0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzwDRLrETkOmylzU7vLF7bfhohUkvvFs',
    appId: '1:329358166515:android:2eca2772023cfd562c2a86',
    messagingSenderId: '329358166515',
    projectId: 'teamtracking-96377',
    storageBucket: 'teamtracking-96377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEw9qvRAyByVDc4HWoKjRDCCI9BPf1D-8',
    appId: '1:329358166515:ios:057df534fd748bfe2c2a86',
    messagingSenderId: '329358166515',
    projectId: 'teamtracking-96377',
    storageBucket: 'teamtracking-96377.appspot.com',
    iosBundleId: 'com.nahitcalisir.TeamTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEw9qvRAyByVDc4HWoKjRDCCI9BPf1D-8',
    appId: '1:329358166515:ios:7e49b35fe1758c642c2a86',
    messagingSenderId: '329358166515',
    projectId: 'teamtracking-96377',
    storageBucket: 'teamtracking-96377.appspot.com',
    iosBundleId: 'com.nahitcalisir.teamTracking.RunnerTests',
  );
}
